name: ArcFaceLoss
weight:

losses:
  - _target_: suprank.losses.ArcFaceLoss
    s: 30.0
    m: 0.50
    easy_margin: False
    hierarchy_level: 0
    num_classes: ${dataset.num_classes_train_level0}
    embedding_size: ${model.net.embed_dim}
    optimizer: ${optimizer.opt.head}
    scheduler: ${optimizer.sch.head}
