name: CSLLoss
weight: [1.]

losses:
  - _target_: suprank.losses.CSLLoss
    hierarchy_level: MULTI
    num_proxies: ${dataset.num_classes_train_level0}
    margins: [0.25, 0.45]
    scale: 32
    embedding_size: ${model.net.embed_dim}
    reduce_type: sum
    optimizer:
      _partial_: true
      _target_: torch.optim.Adam
      lr: 10.0
      weight_decay: 0.0
    scheduler: ${optimizer.sch.head}
