name: NSM
weight:

losses:

  - _target_: suprank.losses.ClusterLoss
    hierarchy_level: 0
    num_classes: ${dataset.num_classes_train_level0}
    embedding_size: ${model.net.embed_dim}
    optimizer: ${optimizer.opt.head}
    scheduler: ${optimizer.sch.head}

  - _target_: suprank.losses.ClusterLoss
    hierarchy_level: 1
    num_classes: ${dataset.num_classes_train_level1}
    embedding_size: ${model.net.embed_dim}
    optimizer: ${optimizer.opt.head}
    scheduler: ${optimizer.sch.head}

  - _target_: suprank.losses.ClusterLoss
    hierarchy_level: 2
    num_classes: ${dataset.num_classes_train_level2}
    embedding_size: ${model.net.embed_dim}
    optimizer: ${optimizer.opt.head}
    scheduler: ${optimizer.sch.head}

  - _target_: suprank.losses.ClusterLoss
    hierarchy_level: 3
    num_classes: ${dataset.num_classes_train_level3}
    embedding_size: ${model.net.embed_dim}
    optimizer: ${optimizer.opt.head}
    scheduler: ${optimizer.sch.head}

  - _target_: suprank.losses.ClusterLoss
    hierarchy_level: 4
    num_classes: ${dataset.num_classes_train_level4}
    embedding_size: ${model.net.embed_dim}
    optimizer: ${optimizer.opt.head}
    scheduler: ${optimizer.sch.head}

  - _target_: suprank.losses.ClusterLoss
    hierarchy_level: 5
    num_classes: ${dataset.num_classes_train_level5}
    embedding_size: ${model.net.embed_dim}
    optimizer: ${optimizer.opt.head}
    scheduler: ${optimizer.sch.head}

  - _target_: suprank.losses.ClusterLoss
    hierarchy_level: 6
    num_classes: ${dataset.num_classes_train_level6}
    embedding_size: ${model.net.embed_dim}
    optimizer: ${optimizer.opt.head}
    scheduler: ${optimizer.sch.head}
