name: ROADRatk_pp
weight:

losses:
  - _target_: suprank.losses.SupRecallLoss
    tau: 0.01
    rho: 100.0
    offset: 1.0
    delta: 0.05
    start: 0.0
    at_k: [1, 2, 4, 8, 16]
    temp: 1.0
    hierarchy_level: 0

  - _target_: suprank.losses.ClusterLoss
    hierarchy_level: 0
    num_classes: ${dataset.num_classes_train_level0}
    embedding_size: ${model.net.embed_dim}
    temperature: 0.05
    optimizer:
      _partial_: true
      _target_: torch.optim.Adam
      lr: 10.0
      weight_decay: 0.0
    scheduler:
      _partial_: true
      _target_: suprank.models.schedulers.CosineAnnealingLR
      T_max: ${max_iter}
      eta_min: 0.1
      last_epoch: -1
