name: ROADMAP
weight: [0.9, 0.1]

losses:
  - _target_: suprank.losses.SupAPLoss
    tau: 0.01
    rho: 100.0
    offset: 1.0
    delta: 0.05
    start: 0.0
    hierarchy_level: 0

  - _target_: suprank.losses.CalibrationLoss
    hierarchy_level: 0
    pos_margin: 0.9
    neg_margin: 0.6
