name: ROADMAP_pp_arch
weight: [0.9, 0.1]

losses:
  - _target_: suprank.losses.SupAPLoss
    tau: 0.01
    rho: 100.0
    offset: 1.0
    delta: 0.05
    start: 0.0
    hierarchy_level: 0

  - _target_: suprank.losses.ArcFaceLoss
    s: 30.0
    m: 0.50
    easy_margin: False
    hierarchy_level: 0
    num_classes: ${dataset.num_classes_train_level0}
    embedding_size: ${model.net.embed_dim}
    optimizer: ${optimizer.opt.head}
    scheduler: ${optimizer.sch.head}
