name: ROAD_NDCG
weight: [0.9, 0.1]

losses:
  - _target_: suprank.losses.SupNDCGLoss
    tau: 0.01
    rho: 100.0
    offset: 1.44
    delta: 0.05
    start: 0.5
    hierarchy_level: MULTI

  - _target_: suprank.losses.ClusterLoss
    hierarchy_level: 0
    num_classes: ${dataset.num_classes_train_level0}
    embedding_size: ${model.net.embed_dim}
    temperature: 0.05
    optimizer: ${optimizer.opt.net}
    scheduler: ${optimizer.sch.net}
