opt:

  backbone:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.000001
    weight_decay: 0.0004

  head:
    _partial_: true
    _target_: torch.optim.Adam
    lr: ${mult:2,${optimizer.opt.backbone.lr}}
    weight_decay: ${optimizer.opt.backbone.weight_decay}

sch:

  backbone:
    _partial_: true
    _target_: suprank.models.schedulers.CosineAnnealingLR
    T_max: ${max_iter}
    eta_min: 0.0
    last_epoch: -1

  head:
    _partial_: true
    _target_: suprank.models.schedulers.CosineAnnealingLR
    T_max: ${max_iter}
    eta_min: 0.0
    last_epoch: -1
