opt:

  backbone:
    _partial_: true
    _target_: torch.optim.SGD
    lr: 0.01
    weight_decay: 0.0001
    momentum: 0.9
    nesterov: True

  head:
    _partial_: true
    _target_: torch.optim.SGD
    lr: ${mult:2,${optimizer.opt.backbone.lr}}
    weight_decay: ${optimizer.opt.backbone.weight_decay}
    momentum: ${optimizer.opt.backbone.momentum}
    nesterov: ${optimizer.opt.backbone.nesterov}

sch:

  backbone:
    _partial_: true
    _target_: suprank.models.schedulers.CosineAnnealingLR
    T_max: ${max_iter}
    eta_min: 0.00001
    last_epoch: -1

  head:
    _partial_: true
    _target_: suprank.models.schedulers.CosineAnnealingLR
    T_max: ${max_iter}
    eta_min: 0.00001
    last_epoch: -1
