sync_bn: True
freeze_batch_norm: True

net:
  _target_: suprank.models.RetrievalNet
  backbone_name: resnet101
  embed_dim: 2048
  norm_features: False
  without_fc: False
  with_autocast: True
  pretrained: True
  whiten: /share/DEEPLEARNING/datasets/image_retrieval/pretrained_models/gldv2_resnet101_gem_normalized_d+2048_imssize+1024x1024.trch
  pooling: gem
