experiment_name: ???
log_dir: /share/DEEPLEARNING/datasets/image_retrieval/experiments/
seed: 0
resume: null

max_iter: 100
warmup_step: null
warmup_keys: [backbone]

print_freq: 50
train_eval_freq: -1
test_eval_freq: 20
save_model: 20

split_batch: ${distributed}
distributed: ${is_cluster}
is_cluster: False
model_parallel: False
num_workers: 10
pin_memory: True

record_gradient: True
gradient_clipping_norm: null

training_loop: base_training_loop

DEBUG: False


defaults:

    - _self_

    - dataset: sop

    - loss: HAPPIER

    - memory: no_memory

    - model: resnet_ln_gem

    - optimizer: sop

    - evaluation: accuracy_calculator

    - override hydra/job_logging: colorlog

    - override hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ${log_dir}/${experiment_name}/outputs

  sweep:
    dir: ${log_dir}
    subdir: ${experiment_name}/outputs
