_target_: suprank.engine.AccuracyCalculator
compute_for_hierarchy_levels: [0]
exclude: []
recall_rate: [4,16,32]
true_recall: []
hard_ap_for_level: []
with_binary_asi: False
overall_accuracy: False
metric_batch_size: 256
inference_batch_size: 256
num_workers: ${num_workers}
pin_memory: ${pin_memory}
convert_to_cuda: True
